package com.wanghaisheng.weiyang.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHANNEL".
 */
public class Channel {

    private Long id;
    private String channel_tag;
    private String channel_title;
    private String channel_json;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Channel() {
    }

    public Channel(Long id) {
        this.id = id;
    }

    public Channel(Long id, String channel_tag, String channel_title, String channel_json) {
        this.id = id;
        this.channel_tag = channel_tag;
        this.channel_title = channel_title;
        this.channel_json = channel_json;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChannel_tag() {
        return channel_tag;
    }

    public void setChannel_tag(String channel_tag) {
        this.channel_tag = channel_tag;
    }

    public String getChannel_title() {
        return channel_title;
    }

    public void setChannel_title(String channel_title) {
        this.channel_title = channel_title;
    }

    public String getChannel_json() {
        return channel_json;
    }

    public void setChannel_json(String channel_json) {
        this.channel_json = channel_json;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
